### PR TITLE
3 more news sections added

### PR DESCRIPTION
**Pull request by ashraysinha6069**
https://ashraysinha6069.github.io/OpenNews/

### CODE REVIEW

**Comment by aswanthkoleri** [comment]
@ashraysinha6069  Its working but resolve the conflicts

**Comment by aswanthkoleri** [comment]
screenshot from 2018-01-11 15-31-21
Fix this

**Comment by ashraysinha6069** [comment]
done

**Comment by aswanthkoleri** [comment]
Good job :+1:

**Pull request merged**
